apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tundra.fullname" . }}
  labels:
    {{- include "tundra.labels" . | nindent 4 }}
data:
  CI_ENVIRONMENT: {{ .Values.config.environment | quote }}
  app.baseURL: {{ .Values.config.baseURL | quote }}
  database.default.hostname: {{ .Values.config.database.hostname | quote }}
  database.default.database: {{ .Values.config.database.name | quote }}
  database.default.port: {{ .Values.config.database.port | quote }}
  database.default.encrypt.ssl_verify: {{ .Values.config.database.sslVerify | quote }}
  database.default.encrypt.ssl_ca: {{ .Values.config.database.sslCA | quote }}
  session.driver: {{ .Values.config.session.driver | quote }}
  session.cookieName: {{ .Values.config.session.cookieName | quote }}
  session.savePath: {{ printf "tcp://%s:%v" .Values.config.redis.host .Values.config.redis.port | quote }}
  cache.handler: {{ .Values.config.cache.handler | quote }}
  cache.redis.host: {{ .Values.config.redis.host | quote }}
  cache.redis.port: {{ .Values.config.redis.port | quote }}
