apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tundra.fullname" . }}
  labels:
    {{- include "tundra.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tundra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tundra.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: tundra
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            {{- include "tundra.env" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
