apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tundra.fullname" . }}
  labels:
    {{- include "tundra.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-username: {{ .Values.secrets.databaseUsername | quote }}
  database-password: {{ .Values.secrets.databasePassword | quote }}
  encryption-key: {{ .Values.secrets.encryptionKey | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
