apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tundra-db-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:717189564438:secret:rds!db-c1601ba7-477a-46a6-9d40-8e7bb55e3931-cyP4sq"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db_username"
          - path: "password"
            objectAlias: "db_password"
  secretObjects:
    - secretName: tundra-db-credentials
      type: Opaque
      data:
        - objectName: "db_username"
          key: DB_USERNAME
        - objectName: "db_password"
          key: DB_PASSWORD